---
- name: ensure locales are installed
  sudo: true
  apt: pkg=locales state=installed

- name: "ensure local locale is set"
  sudo: true
  template: src=locale.j2 dest=/usr/share/i18n/locales owner=root group=root mode=0644

- name: "ensure locale is generated"
  sudo: true
  shell: "locale-gen"

